# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - robot
  categories:
    - title: BUG修复 🐛
      labels:
        - bug
    - title: 重大变化 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: 更新 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: 其他变化
      labels:
        - "*"
