name: 'Bug报告'
about: '提交出现的问题'
title: ''
labels: 'bug'
assignees: 'SingleVrUser'

body:
- type: textarea
  validations:
    required: true
  attributes:
     label: Bug 描述
     description: 请描述你遇到的问题

- type: input
  attributes:
     label: 系统版本
     description: 如果你是在特别的系统版本中运行应用，请注明系统版本
