namespace Display.Models.Dto.OneOneFive;

public class Aria2GlobalOptionRequestResult
{
    public string allowoverwrite { get; set; }
    public string allowpiecelengthchange { get; set; }
    public string alwaysresume { get; set; }
    public string asyncdns { get; set; }
    public string autofilerenaming { get; set; }
    public string autosaveinterval { get; set; }
    public string btdetachseedonly { get; set; }
    public string btenablehookafterhashcheck { get; set; }
    public string btenablelpd { get; set; }
    public string btforceencryption { get; set; }
    public string bthashcheckseed { get; set; }
    public string btloadsavedmetadata { get; set; }
    public string btmaxopenfiles { get; set; }
    public string btmaxpeers { get; set; }
    public string btmetadataonly { get; set; }
    public string btmincryptolevel { get; set; }
    public string btremoveunselectedfile { get; set; }
    public string btrequestpeerspeedlimit { get; set; }
    public string btrequirecrypto { get; set; }
    public string btsavemetadata { get; set; }
    public string btseedunverified { get; set; }
    public string btstoptimeout { get; set; }
    public string bttrackerconnecttimeout { get; set; }
    public string bttrackerinterval { get; set; }
    public string bttrackertimeout { get; set; }
    public string cacertificate { get; set; }
    public string checkcertificate { get; set; }
    public string checkintegrity { get; set; }
    public string conditionalget { get; set; }
    public string confpath { get; set; }
    public string connecttimeout { get; set; }
    public string consoleloglevel { get; set; }
    public string contentdispositiondefaultutf8 { get; set; }
    public string _continue { get; set; }
    public string daemon { get; set; }
    public string deferredinput { get; set; }
    public string dhtfilepath { get; set; }
    public string dhtfilepath6 { get; set; }
    public string dhtlistenport { get; set; }
    public string dhtmessagetimeout { get; set; }
    public string dir { get; set; }
    public string disableipv6 { get; set; }
    public string diskcache { get; set; }
    public string downloadresult { get; set; }
    public string dryrun { get; set; }
    public string dscp { get; set; }
    public string enablecolor { get; set; }
    public string enabledht { get; set; }
    public string enabledht6 { get; set; }
    public string enablehttpkeepalive { get; set; }
    public string enablehttppipelining { get; set; }
    public string enablemmap { get; set; }
    public string enablepeerexchange { get; set; }
    public string enablerpc { get; set; }
    public string eventpoll { get; set; }
    public string fileallocation { get; set; }
    public string followmetalink { get; set; }
    public string followtorrent { get; set; }
    public string forcesave { get; set; }
    public string ftppasv { get; set; }
    public string ftpreuseconnection { get; set; }
    public string ftptype { get; set; }
    public string hashcheckonly { get; set; }
    public string help { get; set; }
    public string httpacceptgzip { get; set; }
    public string httpauthchallenge { get; set; }
    public string httpnocache { get; set; }
    public string humanreadable { get; set; }
    public string keepunfinisheddownloadresult { get; set; }
    public string listenport { get; set; }
    public string loglevel { get; set; }
    public string lowestspeedlimit { get; set; }
    public string maxconcurrentdownloads { get; set; }
    public string maxconnectionperserver { get; set; }
    public string maxdownloadlimit { get; set; }
    public string maxdownloadresult { get; set; }
    public string maxfilenotfound { get; set; }
    public string maxmmaplimit { get; set; }
    public string maxoveralldownloadlimit { get; set; }
    public string maxoveralluploadlimit { get; set; }
    public string maxresumefailuretries { get; set; }
    public string maxtries { get; set; }
    public string maxuploadlimit { get; set; }
    public string metalinkenableuniqueprotocol { get; set; }
    public string metalinkpreferredprotocol { get; set; }
    public string minsplitsize { get; set; }
    public string mintlsversion { get; set; }
    public string netrcpath { get; set; }
    public string noconf { get; set; }
    public string nofileallocationlimit { get; set; }
    public string nonetrc { get; set; }
    public string optimizeconcurrentdownloads { get; set; }
    public string parameterizeduri { get; set; }
    public string pausemetadata { get; set; }
    public string peeragent { get; set; }
    public string peeridprefix { get; set; }
    public string piecelength { get; set; }
    public string proxymethod { get; set; }
    public string quiet { get; set; }
    public string realtimechunkchecksum { get; set; }
    public string remotetime { get; set; }
    public string removecontrolfile { get; set; }
    public string retrywait { get; set; }
    public string reuseuri { get; set; }
    public string rlimitnofile { get; set; }
    public string rpcalloworiginall { get; set; }
    public string rpclistenall { get; set; }
    public string rpclistenport { get; set; }
    public string rpcmaxrequestsize { get; set; }
    public string rpcsaveuploadmetadata { get; set; }
    public string rpcsecure { get; set; }
    public string savenotfound { get; set; }
    public string savesession { get; set; }
    public string savesessioninterval { get; set; }
    public string seedratio { get; set; }
    public string serverstattimeout { get; set; }
    public string showconsolereadout { get; set; }
    public string showfiles { get; set; }
    public string socketrecvbuffersize { get; set; }
    public string split { get; set; }
    public string stderr { get; set; }
    public string stop { get; set; }
    public string streampieceselector { get; set; }
    public string summaryinterval { get; set; }
    public string timeout { get; set; }
    public string truncateconsolereadout { get; set; }
    public string uriselector { get; set; }
    public string usehead { get; set; }
    public string useragent { get; set; }
}